version: '3'
services:

  frontend:
    image: okteto.dev/boxthatminigame-client:v1
    container_name: boxthatminigame-frontend
    build: ./client
    depends_on:
      - server
    volumes:
      - ./client:/usr/src/app
    ports: 
      - '4200:4200'
    command:
      ng serve --configuration=production --host 0.0.0.0 --port 4200
  server:
    container_name: boxthatminigame-backend
    image: okteto.dev/boxthatminigame-server:v1
    build:
      context: ./server
    depends_on:
      - postgres-db
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: postgres-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nickolas123!
      DB_NAME: boxthatminigame

  postgres-db:
    container_name: postgres-db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nickolas123!
      - POSTGRES_DB=boxthatminigame
    ports:
      - '5432:5432'
    volumes:
      - pgdata1:/var/lib/posgressql/data
    

volumes:
  pgdata1: {}