services:

  server:
    container_name: boxthatminigame-backend
    image: okteto.dev/boxthatminigame-server:v1
    build:
      context: ./server
    depends_on:
      - db
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: Nickolas123!
      DB_NAME: boxthatminigame

  db:
    container_name: db
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Nickolas123!
      - POSTGRES_DB=boxthatminigame
    ports:
      - '5432:5432'
    volumes:
      - pgdata1:/var/lib/posgressql/data
    

volumes:
  pgdata1: {}